### ISSUE TITLE
setMode() passes in band and mode, but ci-v protocol only uses mode

### ISSUE THREAD

**Issue by gx1400** [hb9ssb/trx-control#10]
https://github.com/hb9ssb/trx-control/blob/1e86670be40e8157e0d4373dccd765391d98fd02/sbin/trxd/trx-controller.lua#L72

https://github.com/hb9ssb/trx-control/blob/1e86670be40e8157e0d4373dccd765391d98fd02/protocol/ci-v.lua#L114

**Comment by mbalmer** [comment]
Has been fixed. btw, some trx use the term band, other vfa etc.  What is needed is a common naming scheme that should be documented.
