### ISSUE TITLE
bug : lock/unlock functions not functional

### ISSUE THREAD

**Issue by gx1400** [hb9ssb/trx-control#18]
I noted on the following line that the trxctl commands are `lock-trx` and `unlock-trx`
https://github.com/hb9ssb/trx-control/blob/098188da2a181c9a04f58dcb21a537f72084d122/sbin/trxd/trx-controller.lua#L91

I also noted that the function call being made is `driver.setLock()`, whereas ci-v.lua used `lock`.  I noticed that protocol/cat-delimited.lua uses `setLock` and `setUnlock`

I updated the function names in ci-v.lua (here https://github.com/hb9ssb/trx-control/commit/d4ab1a8e76110477da9b2f508ac3e37ba818612b) in an attempt to work on implementing the lock/unlock function in the ci-v protocol on the IC-7300

With those two changes in place I receive these errors in trxd.

```
socket-handler: <- {"request":"unlock-trx","to":"ic7300"}
trxd[12133]: Lua error: /usr/share/trxd/trx-controller.lua:94: attempt to call a nil value (method 'setUnlock')
socket-sender: -> {"status":"Error","reason":"Lua error"}
socket-handler: <- {"request":"lock-trx","to":"ic7300"}
trxd[12133]: Lua error: /usr/share/trxd/trx-controller.lua:92: attempt to call a nil value (method 'setLock')
socket-sender: -> {"status":"Error","reason":"Lua error"}
```

I am probably missing some changes. Please advise.

**Comment by mbalmer** [comment]
Closing this as trxd(8) now reports proper failure messages.
