### ISSUE TITLE
Machine-readable output for `trxctl`

### ISSUE THREAD

**Issue by corvus-ch** [hb9ssb/trx-control#24]
Sometimes, a simple script is all that is needed. Having utilities with machine-readable output, simplifies writing those scripts. In context of `trx-control`, that would apply to `trxctl`. Consider the following examples:

```sh
$ trxctl --output=json @my-rig get-frequency | jq -r '.frequency'
145500000
$ trxctl -o json get-fix | jq -r '.fix.locator'
JN47bj
$ trxctl --output json @my-rig info | jq '.operatingModes'
"['rtty-lsb', 'data-lsb', 'rtty-usb, …]"
```

**Comment by mbalmer** [comment]
That is actually straight forward to do, as the reply from from trxd(8) is JSON formatted anyways.Am 11.10.2024 um 16:03 schrieb Christian Häusler ***@***.***>:﻿
Sometimes, a simple script is all that is needed. Having utilities with machine-readable output, simplifies writing those scripts. In context of trx-control, that would apply to trxctl. Consider the following examples:
$ trxctl --output=json @my-rig get-frequency | jq -r '.frequency'
145500000
$ trxctl -o json get-fix | jq -r '.fix.locator'
JN47bj
$ trxctl --output json @my-rig info | jq '.operatingModes'
"['rtty-lsb', 'data-lsb', 'rtty-usb, …]"

**Comment by corvus-ch** [comment]
Thanks.
