### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by mbalmer** [hb9ssb/trx-control#28]
An optional authentication mechanism is needed for both plain sockets and WebSockets, so that trxd(8) can safely expose its connection endpoints on the internet.

Possible solutions:

- Basic authentication using a username and password
- Using client certificates
- ...

**Comment by HB9HIL** [comment]
I like the Client Certificate Solution :)

**Comment by mbalmer** [comment]
Client certificates for WebSockets are now available.  For plain sockets, I must first add TLS support.  This will happen sooner or later.
